services:
  - type: web
    name: burgerflow-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    envVars:
      - key: WHATSAPP_ENABLED
        value: "false"
      - key: NODE_ENV
        value: production
